# Generated by Django 3.1.2 on 2020-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refri_number', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('ingredient', models.CharField(max_length=50, null=True)),
                ('ingredient_name', models.CharField(max_length=50, null=True)),
                ('seasoning', models.CharField(max_length=50, null=True)),
                ('seasoning_name', models.CharField(max_length=50, null=True)),
                ('howto', models.CharField(max_length=500, null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(max_length=100, null=True)),
                ('recipe_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RECOMM_RECIPE',
            },
        ),
    ]
