# Generated by Django 3.1.2 on 2020-12-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecipe',
            name='howto',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='ingredient',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='ingredient_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='seasoning',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='seasoning_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='howto',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='ingredient',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='ingredient_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='seasoning',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='seasoning_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
