# Generated by Django 3.1.2 on 2020-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdata', '0003_allrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecipe',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allrecipe',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommrecipe',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
