# Generated by Django 3.1.2 on 2020-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fridge_number', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PHOTO_TEST',
            },
        ),
    ]
