# Generated by Django 3.1.4 on 2020-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='alarm_mode',
            field=models.IntegerField(default=0),
        ),
    ]
