# Generated by Django 3.1.2 on 2020-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
