# Generated by Django 3.1.2 on 2020-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('fridge_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('motion_sensor_on_off', models.IntegerField(default=0)),
                ('motion_period', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'REFRIGERATOR',
            },
        ),
        migrations.CreateModel(
            name='Seosor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fridge_number', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SENSOR',
            },
        ),
        migrations.RenameModel(
            old_name='PhotoTest',
            new_name='Photo',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='PHOTO',
        ),
    ]
