# Generated by Django 3.1.2 on 2020-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0002_photo_file_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seosor',
            new_name='Sensor',
        ),
    ]
