# Generated by Django 3.1.2 on 2020-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('following_user_id', models.CharField(max_length=500, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'FOLLOW',
            },
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('recipe_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RECIPE_FAVORITE',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=500, null=True)),
                ('user_email', models.CharField(max_length=500, null=True)),
                ('user_name', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('guardian_name', models.CharField(max_length=500, null=True)),
                ('guardian_phone_number', models.CharField(max_length=500, null=True)),
                ('purpose', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'USER_INFO',
            },
        ),
    ]
