# Generated by Django 3.1.2 on 2020-12-15 06:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
