# Generated by Django 3.1.2 on 2020-12-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='guardian_email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
