# Generated by Django 3.1.4 on 2020-12-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alarm'),
        ('user', '0002_auto_20201215_1534'),
    ]

    operations = [
    ]
