# Generated by Django 3.1.2 on 2020-12-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201212_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipefavorite',
            old_name='recipe_num',
            new_name='all_recipe_id',
        ),
    ]
