# Generated by Django 3.1.2 on 2020-12-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_guardian_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Follow',
        ),
    ]
