# Generated by Django 3.1.2 on 2020-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllGrocery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ALL_GROCERY',
            },
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, null=True)),
                ('all_grocery_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('gubun', models.IntegerField(blank=True, null=True)),
                ('coordinate', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'GROCERY',
            },
        ),
    ]
