# Generated by Django 3.1.2 on 2020-12-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='all_grocery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='cordiname',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
