# Generated by Django 3.1.4 on 2020-12-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgrocery',
            name='name_english',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
