# Generated by Django 3.1.2 on 2020-12-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20201212_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='cordiname',
            new_name='cordinate',
        ),
    ]
