# Generated by Django 3.1.2 on 2020-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20201208_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='reg_time',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='reg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
