# Generated by Django 3.1.4 on 2020-12-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_allgrocery_name_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgrocery',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='allgrocery',
            name='name_english',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='coordinate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
