# Generated by Django 3.1.2 on 2020-12-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20201212_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='gubun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
